### ISSUE TITLE
Regarding code issues

### ISSUE THREAD

**Issue by wu-gang123** [STAC-USC/Graph-signal-sampling-AVM#1]
The file does not contain a main program. Can you provide the main program? I wanna know how to obtain the image in the file. 
Thank you!!!

**Comment by ajinkyajayawant** [comment]
The demo_sample_and_reconstruct.m file contains the function
demo_sample_and_reconstruct
which you can treat as the main function. It takes two arguments

   1. Path where gspbox is installed
   2. Path where GraphSamplingBox is installed

Example usage:

demo_sample_and_reconstruct('~/Downloads/gspbox',
'~/Downloads/GraphSamplingBox');

**Comment by wu-gang123** [comment]
thank you very much！！！having a nice day!
